.equ TIPM_LOCK 		 	 -15 
.equ IPL_LOCK 		 	 251658240 
.equ PSW_I_MASK 		 	 65536 
.equ PSW_IPL_MASK 		 	 117440512 
.equ EXC_GET_PSW_OFFSET 		 	 80 


.equ LOG_INH_ENTER 	 	 0 
.equ LOG_INH_LEAVE 	 	 0 
.equ LOG_EXC_ENTER 	 	 0 
.equ LOG_EXC_LEAVE 	 	 0 
.equ LOG_DSP_ENTER 	 	 0 
.equ LOG_DSP_LEAVE 	 	 0 
.equ SIL_DLY_TIM1 	 	 69 
.equ SIL_DLY_TIM2 	 	 50 
/*
 *  Architecture-dependent Definitions (RX64m)
 */


