name: Test Espressif examples on various official Docker containers
concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  espressif_latest:
    name: Test Espressif on latest Docker container
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Espressif IDE and build examples
        run: . /opt/esp/idf/export.sh; IDE/Espressif/ESP-IDF/compileAllExamples.sh
  espressif_v4_4:
    name: Test Espressif on v4.4 Docker container
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.4
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Espressif IDE and build examples
        run: . /opt/esp/idf/export.sh; IDE/Espressif/ESP-IDF/compileAllExamples.sh
  espressif_v5_0:
    name: Test Espressif on v5.0 Docker container
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.0
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Espressif IDE and build examples
        run: . /opt/esp/idf/export.sh; IDE/Espressif/ESP-IDF/compileAllExamples.sh
